name: IronHavenSB
author: CraftYun38(Iron Haven Developer)
version: 1.0
main: com.skycraft.skyblock.Main
api-version: 1.16
depend: [WorldEdit, Vault]

commands:
  spawn:
    description: Teleport to spawn!
  is:
    description: Skyblock main command!